---
title: Publications
description: Publications
engine: knitr
hidetopnav: true
---

```{css}
#| label: style
#| echo: FALSE

ul li:before {
  content: "";
  margin: 0;
}

ul li p {
  margin-left: 0;
}

ul li p, .sidenote {
  font-size: 80%;
  line-height: 1.4;
}

ul li a {
  padding: 0 2px 0 2px;
}
```

Selection of publications. For a full list see my [Google Scholar profile](https://scholar.google.com/citations?user=QmVQcsAAAAAJ&hl=en)

{{{< sidenote >}}}
2024
{{{< /sidenote >}}}

  - **D Roelfs**, D van der Meer, D Alnæs, O Frei, AA Shadrin, R Loughnan, CC Fan, AM Dale, OA Andreassen, LT Westlye, T Kaufmann (2024) [***Genetic overlap between multivariate measures of human functional brain connectivity and psychiatric disorders***](https://doi.org/10.1038/s44220-023-00190-1). _Nature Mental Health_. doi: [10.1038/s44220-023-00190-1](https://doi.org/10.1038/s44220-023-00190-1) preprint: [10.1101/2021.06.15.21258954](https://doi.org/10.1101/2021.06.15.21258954)
  
  - 

{{{< sidenote >}}}
2023
{{{< /sidenote >}}}

  - **D Roelfs**, O Frei, D van der Meer, E Tissink, A Shadrin, D Alnæs, OA Andreassen, LT Westlye, T Kaufmann (2023) [***Shared genetic architecture between mental health and the brain functional connectome in the UK Biobank***](https://doi.org/10.1186/s12888-023-04905-7). _BMC Psychiatry_. doi: [10.1186/s12888-023-04905-7](https://doi.org/10.1186/s12888-023-04905-7) preprint: [10.1101/2022.06.24.22276846](https://doi.org/10.1101/2022.06.24.22276846)

  - NB Slapø, KN Jørgensen, T Elvsåshagen, S Nerland, **D Roelfs**, M Valstad, CMF Timpe, G Richard, D Beck, LS Sæther, MCF Werner, TV Lagerberg, OA Andreassen, I Melle, I Agartz, LT Westlye, T Moberget, EG Jönsson (2023) [***Relationship between function and structure in the visual cortex in healthy individuals and in patients with severe mental disorders***](https://doi.org/10.1016/j.pscychresns.2023.111633). _Psychiatry Research: Neuroimaging_. doi: [10.1016/j.pscychresns.2023.111633](https://doi.org/10.1016/j.pscychresns.2023.111633)

  - LS Sæther, T Ueland, B Haatveit, LA Maglanoc, A Szabo, S Djurovic, P Aukrust, **D Roelfs**, C Mohn, MBEG Ormerud, TV Lagerberg, NE Steen, I Melle, OA Andreassen, T Ueland (2023) [***Inflammation and cognition in severe mental illness: patterns of covariation and subgroups***](https://doi.org/10.1038/s41380-022-01924-w). _Molecular Psychiatry_. doi: [10.1038/s41380-022-01924-w](https://doi.org/10.1038/s41380-022-01924-w) preprint: [10.1101/2022.08.25.22279209](https://doi.org/10.1101/2022.08.25.22279209)

{{{< sidenote >}}}
2022
{{{< /sidenote >}}}

  - G Hindley, O Frei, AA Shadrin, W Cheng, KS O'Connoll, R Icick, N Parker, S Bahrami, N Karadag, **D Roelfs**, B Holen, A Lin, CC Fan, S Djurovic, AM Dale, OB Smeland, OA Andreassen (2022) [***Charting the Landscape of Genetic Overlap Between Mental Disorders and Related Traits Beyond Genetic Correlation***](https://doi.org/10.1176/appi.ajp.21101051). _The American Journal of Psychiatry_. doi: [10.1176/appi.ajp.21101051](https://doi.org/10.1176/appi.ajp.21101051)

  - D van der Meer, T Kaufmann, AA Shadrin, C Makowski, O Frei, **D Roelfs**, J Monereo Sanchez, DEJ Linden, J Rokicki, D Alnæs, C de Leeuw, WK Thompson, R Loughnan, C Chieh Fan, PM Thompson, LT Westlye, OA Andreassen, AM Dale (2022) [***The genetic architecture of human cortical folding***](https://doi.org/10.1126/sciadv.abj9446). _Science Advances_. doi: [10.1101/ 2021.01.13.426555](https://doi.org/10.1126/sciadv.abj9446) preprint: [10.1101/ 2021.01.13.426555](https://doi.org/10.1101/2021.01.13.426555)
  
{{{< sidenote >}}}
2021
{{{< /sidenote >}}}

  - LS Sæther, **D Roelfs**, T Moberget, OA Andreassen, T Elvsåshagen, EG Jönsson, A Vaskinn (2021) [***Exploring neurophysiological markers of visual perspective taking: Methodological considerations***](https://doi.org/10.1016/j.ijpsycho.2020.12.006). _International Journal of Psychophysiology_. doi: [10.1016/j.ijpsycho.2020.12.006](https://doi.org/10.1016/j.ijpsycho.2020.12.006)

  - **D Roelfs**, D Alnæs, O Frei, D van der Meer, OB Smeland, OA Andreassen, LT Westlye, T Kaufmann (2021) [***Phenotypically independent profiles relevant to mental health are genetically correlated***](https://doi.org/10.1038/s41398-021-01313-x). _Translational Psychiatry_. doi: [10.1038/s41398-021-01313-x](https://doi.org/10.1038/s41398-021-01313-x) preprint: [10.1101/2020.03.30.20045591](https://doi.org/10.1101/2020.03.30.20045591)

{{{< sidenote >}}}
2020
{{{< /sidenote >}}}

  - I Voldsbekk, I Groote, N Zak, **D Roelfs**, O Geier, P Due-Tønnesen, LL Løkken, M Strømstad, TY Blakstvedt, YS Kuiper, T Elvsåshagen, LT Westlye, A Bjørnerud, II Maximov (2020) [***Sleep and sleep deprivation differentially alter white matter microstructure: A mixed model design utilising advanced diffusion modelling***](https://doi.org/10.1016/j.neuroimage.2020.117540). _NeuroImage_. doi: [j.neuroimage.2020.117540](https://doi.org/10.1016/j.neuroimage.2020.117540) preprint: [10.1101/ 2020.08.24.259432](https://doi.org/10.1101/2020.08.24.259432)

  - M Valstad, T Moberget, **D Roelfs**, NB Slapø, CMF Timpe, D Beck, G Richard, LS Sæther, B Haatveit, KA Skaug, JE Nordvik, C Hatlestad-Hall, GT Einevoll, T Mãki-Marttunen, LT Westlye, EG Jõnsson, OA Andreassen, T Elvsåshagen (2020) [***Experience-dependent modulation of the visual evoked potential: Testing effect sizes, retention over time, and associations with age in 415 healthy individuals***](https://doi.org/10.1016/j.neuroimage.2020.117302). _NeuroImage_. doi: [10.1016/j.neuroimage.2020.117302](https://doi.org/10.1016/j.neuroimage.2020.117302)

  - I Voldsbekk, II Maximov, N Zak, **D Roelfs**, O Geier, P Due-Tønnessen, T Elvsåshagen, M Strømstad, A Bjørnerud, I Groote (2020) [***Evidence for wakefulness-related changes to extracellular space in human brain white matter from diffusion-weighted MRI***](https://doi.org/10.1016/j.neuroimage.2020.116682). _NeuroImage_. doi: [10.1016/j.neuroimage.2020.116682](https://doi.org/10.1016/j.neuroimage.2020.116682)
