---
description: "publications"
slug: "publications"
thumbnail: "images/avatar.png"
title: "Publications"
author: "Daniel Roelfs"
output:
  html_document:
    keep_md: yes
---

<ul style="list-style-type: circle;">
  <li>**PREPRINT** **D Roelfs**, D van der Meer, D Alnæs, O Frei, R Loughnan, CC Fan, AM Dale, OA Andreassen, LT Westlye, T Kaufmann (2021) [***Genetic overlap between multivariate measures of human functional brain connectivity and psychiatric disorders***](https://doi.org/10.1101/2021.06.15.21258954). _medRxiv_. doi: [10.1101/2021.06.15.21258954](https://doi.org/10.1101/2021.06.15.21258954)</li>

  <li>**D Roelfs**, D Alnæs, O Frei, D van der Meer, OB Smeland, OA Andreassen, LT Westlye, T Kaufmann (2021) [***Phenotypically independent profiles relevant to mental health are genetically correlated***](https://doi.org/10.1038/s41398-021-01313-x). _Translational Psychiatry_. doi: [10.1038/s41398-021-01313-x](https://doi.org/10.1038/s41398-021-01313-x) preprint: [10.1101/2020.03.30.20045591](https://doi.org/10.1101/2020.03.30.20045591)</li>

  <li>**PREPRINT** D van der Meer, T Kaufmann, AA Shadrin, C Makowski, O Frei, **D Roelfs**, J Monereo Sanchez, DEJ Linden, Jaroslav Rokicki, C de Leeuw, WK Thompson, TJ Loughnan, CC Fan, PM Thompson, LT Westlye, OA Andreassen, AM Dale (2021) [***The genetic architecture of human cortical folding***](https://doi.org/10.1101/2021.01.13.426555). _bioRxiv_. doi: [10.1101/ 2021.01.13.426555](https://doi.org/10.1101/2021.01.13.426555)</li>

  <li>I Voldsbekk, I Groote, N Zak, **D Roelfs**, O Geier, P Due-Tønnesen, LL Løkken, M Strømstad, TY Blakstvedt, YS Kuiper, T Elvsåshagen, LT Westlye, A Bjørnerud, II Maximov (2020) [***Sleep and sleep deprivation differentially alter white matter microstructure: A mixed model design utilising advanced diffusion modelling***](https://doi.org/10.1016/j.neuroimage.2020.117540). _NeuroImage_. doi: [j.neuroimage.2020.117540](https://doi.org/10.1016/j.neuroimage.2020.117540) preprint: [10.1101/ 2020.08.24.259432](https://doi.org/10.1101/2020.08.24.259432)</li>

  <li>M Valstad, T Moberget, **D Roelfs**, NB Slapø, CMF Timpe, D Beck, G Richard, LS Sæther, B Haatveit, KA Skaug, JE Nordvik, C Hatlestad-Hall, GT Einevoll, T Mãki-Marttunen, LT Westlye, EG Jõnsson, OA Andreassen, T Elvsåshagen (2020) [***Experience-dependent modulation of the visual evoked potential: Testing effect sizes, retention over time, and associations with age in 415 healthy individuals***](https://doi.org/10.1016/j.neuroimage.2020.117302). _NeuroImage_. doi: [10.1016/j.neuroimage.2020.117302](https://doi.org/10.1016/j.neuroimage.2020.117302)</li>

  <li>I Voldsbekk, II Maximov, N Zak, **D Roelfs**, O Geier, P Due-Tønnessen, T Elvsåshagen, M Strømstad, A Bjørnerud, I Groote (2020) [***Evidence for wakefulness-related changes to extracellular space in human brain white matter from diffusion-weighted MRI***](https://doi.org/10.1016/j.neuroimage.2020.116682). _NeuroImage_. doi: [10.1016/j.neuroimage.2020.116682](https://doi.org/10.1016/j.neuroimage.2020.116682)</li>
<ul>