
[build] 
  command = "hugo --gc --minify"
  publish = "public"

[context.production.environment]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.140.2" 
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.140.2"

[context.branch-deploy]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.140.2" 

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
