---
description: "photography"
slug: "photography"
thumbnail: "images/avatar.png"
title: "Photography"
author: "Daniel Roelfs"
output:
  html_document:
    keep_md: yes
---

In my free time I enjoy photography. Since I live in Norway, every hike is an opportunity to see some amazing landscapes. Besides that my interests also extend to cityscapes, lifestyle pictures, and portraits.

See the website for my phography website here: <a href="photography.danielroelfs.com" target="_blank">photography.danielroelfs.com</a>

```{r, echo=FALSE}
htmltools::tags$iframe(src = "https://photography.danielroelfs.com/", 
                       onload = "this.width='105%';this.height=screen.height*1.1;",
                       frameBorder="0")
```

```{r, echo=FALSE, eval=FALSE}
htmltools::tags$iframe(src = "photography.html", 
                       onload = "this.width='105%';this.height=screen.height*1.1;",
                       frameBorder="0")
```

<!--<font size="3">All photos are available as high-resolution images and print. Send me an e-mail at [daniel.roelfs[at]medisin.uio.no](daniel.roelfs@medisin.uio.no) for the details!</font>-->