---
title: Curriculum Vitae
description: Curriculum Vitae
engine: knitr
---

```{css}
#| echo: false

ul {
  margin-top: 0.5rem;
  padding-left: 0;
}

li {
  font-size: 80%;
  padding: 0;
  max-width: 80%;
}

ul li:before {
  margin-right: 10px;
}

ol li p, ul li p {
  margin-left: 1.5rem;
  padding-left: 10px;
  width: 80%;
}

ol li:only-child {
  margin-left: 1.5rem;
}

p {
  margin-top: 0;
  margin-bottom: 0.1rem;
}

h3 {
  font-size: 1.4rem;
  margin-top: 0.75rem;
  margin-bottom: 0rem;
  width: 62.5%;
}

@media (max-width: 760px) {
  h3 {
    width: 100%;
  }
}

.cv-date {
  font-style: italic;
  margin-top: 0;
  float: right;
}

.smaller-text {
  font-size: 80%;
  line-height: 1;
}

.progress {
  font-family: 'Cooper Hewitt', sans-serif;
  font-weight: 711;
  width: 45%;
  height: 1.6rem;
  padding: 1px;
  margin: 0.15rem 0;
  background: rgba(0, 0, 0, 0.1);
}

@media (max-width: 760px) {
  .progress {
    width: 100%;
  }
}

.progress-bar {
  font-size: 1.3rem;
  color: white;
  height: 1.6rem;
  box-shadow: 0 0 0 0 none, inset 0 1px rgba(255, 255, 255, 0.1);
}

.progress > .progress-bar {
  padding-left: 5px;
  font-variant-caps: all-small-caps;
  background-color: #555;
}
```

For a downloadable version of this CV, go to [cv.danielroelfs.com](https://cv.danielroelfs.com)

---

## Work Experience

### Storebrand - Digital - Analytics & AI {{{< cv-date >}}}feb 2026 - current{{{< /cv-date >}}}

_Data Scientist_

- Data science projects across various departments in the group

- Implementing robust machine learning and (generative) AI models for various use cases

- Using (among others) Databricks, Snowflake, Dagster, and accompanying best practices

### DNB - Group Security - Group AML {{{< cv-date >}}}aug 2022 - jan 2026{{{< /cv-date >}}}

_Data Scientist_

- Data scientist in the Anti-Money Laundering Group at DNB

- Creating machine learning models using Python, R, and AWS cloud services and putting models in production

- Application of responsible data science practices in both development and deployment

### University of Oslo - NORMENT - Multimodal Imaging Group {{{< cv-date >}}}mar 2019 - jul 2022{{{< /cv-date >}}}

_Doctoral Research Fellow_

- PhD position on neuroimaging and genetics

- Running a study from conception through writing the final manuscript

- Writing scripts and pipelines in R, Python, and MATLAB{{{< marginnote >}}}all code is available on [GitHub](https://github.com/norment/open-science){{{< /marginnote >}}}

### University of Oslo - NORMENT - EEG Group {{{< cv-date >}}}may 2018 - feb 2019{{{< /cv-date >}}}

_Research Assistant_

- Managing EEG data, data preprocessing and analysis, training new EEG testers, performing EEG experiments

- Maintaining and adapting preprocessing pipelines for EEG data

### Rikshospitalet - Department of Medical Physics {{{< cv-date >}}}may 2018 - feb 2019{{{< /cv-date >}}}

_Research Assistant_

- Data collection, managment, and processing in an MRI study on sleep deprivation

- Preprocessing and analyzing the imaging data and preparing datasets for collaborators

- Processing and analyzing of data from the video camera

---

## Education

### University of Oslo - Faculty of Clinical Medicine {{{< cv-date >}}}mar 2019 - jul 2022{{{< /cv-date >}}}

_PhD, Doctoral Education_

- Doctoral education at the Institute of Clinical Medicine at the University of Oslo{{{< marginnote >}}}thesis available online [here](https://thesis.danielroelfs.app){{{< /marginnote >}}}

- Courses relevant to neurobiology, advanced statistics, and other academic and non-academic skills

### Lund University - Faculty of Medicine {{{< cv-date >}}}sep 2016 - may 2018{{{< /cv-date >}}}

_MSc, Biomedicine_

- Master’s program in Biomedicine at the Faculty of Medicine

- Focus on molecular biology and neuroscience

### Utrecht University - University College Roosevelt {{{< cv-date >}}}sep 2012 - may 2015{{{< /cv-date >}}}

_BSc, pre-medical track_

- Major in the pre-medical science track, minor in philosophy

- Liberal Arts & Science program

- Honors College

---

## Skills & Languages

Daily use of Python, R, SQL (various dialects), bash, AWS, Databricks, Snowflake, Git, and common packages and module. Experience also with MATLAB, LaTeX, HTML/CSS. Have previously worked with Google Cloud, SLURM.{{{< marginnote >}}}some of these skills are documented on [GitHub](https://github.com/danielroelfs) also{{{< /marginnote >}}}

{{{< gap "0.5rem" >}}}

{{{< smaller-text >}}}
In addition, I’m familiar with common data science and data engineering frameworks including but not limited to [Shiny](https://shiny.posit.co), [Flask](https://flask.palletsprojects.com/en/stable/), [Streamlit](https://streamlit.io), [MLFlow](https://mlflow.org), [Airflow](https://airflow.apache.org), [dbt](https://www.getdbt.com), [Docker](https://www.docker.com), [Snowflake](https://www.snowflake.com), [AWS](https://aws.amazon.com), [LangChain](https://www.google.com/search?client=safari&rls=en&q=langchain&ie=UTF-8&oe=UTF-8), and various other common tools.
{{{< /smaller-text >}}}

{{{< gap "1.5rem" >}}}

{{{< progress-bar perc="99" >}}} Dutch (native) {{{< /progress-bar >}}}

{{{< progress-bar perc="99" >}}} English (C2) {{{< /progress-bar >}}}

{{{< progress-bar perc="99" >}}} Norwegian (C2) {{{< /progress-bar >}}}

{{{< progress-bar perc="55" >}}} French (C1) {{{< /progress-bar >}}}

{{{< progress-bar perc="45" >}}} German (A2) {{{< /progress-bar >}}}

---

## Awards

### ECIP Oral Finalist {{{< cv-date >}}} 2021 {{{< /cv-date >}}}

_World Congress of Psychiatry Genetics_

- {{{< p >}}}Awarded to promising oral presentations from early-career researchers{{{< /p >}}}

### International Training Grant {{{< cv-date >}}} 2019 {{{< /cv-date >}}}

_Norwegian Research School in Neuroscience_

- {{{< p >}}}Grant awarded to scientists to receive training abroad that’ll benefit their research in Norway{{{< /p >}}}

### Sparbanken Skåne Master Prize {{{< cv-date >}}} 2019 {{{< /cv-date >}}}

_Sparbanksstiftelsen Färs & Frosta, Lund University_

- {{{< p >}}}Awarded to the best master theses in the field of neuroscience{{{< /p >}}}

---

## Commissions

### DNB Data Science Meetup {{{< cv-date >}}}oct 2023 - dec 2024{{{< /cv-date >}}}

_Committee Member_

### Norwegian Research School in Neuroscience {{{< cv-date >}}}sep 2019 - may 2021{{{< /cv-date >}}}

_Committee Member_

- {{{< p >}}}Organization of the national conference for neuroscience PhD candidates{{{< /p >}}}

### The Netherlands Red Cross Student Desk Zeeland {{{< cv-date >}}}jan 2014 - may 2015{{{< /cv-date >}}}

_General Board Member (Fundraising portfolio)_

---

## Portfolio

[danielroelfs.com](https://danielroelfs.com)

[danielroelfs.app](https://danielroelfs.app)

[Talks & Presentations](https://slides.danielroelfs.app)

[Bilkollektivet Trip Cost Calculator](https://bilkollektivet.danielroelfs.app)

[Advent of SQL](https://danielroelfs.github.io/advent-of-sql/)

[Advent of Code](https://danielroelfs.github.io/advent-of-code/)

[Introduction To Basic Statistics in R](https://norment.github.io/IntroToBasicStatisticsInR/)

---

## Publications

See the [publications](/publications) page, [ORCID](https://orcid.org/0000-0002-1083-002X) or my [Google Scholar](https://scholar.google.com/citations?hl=en&user=QmVQcsAAAAAJ&view_op=list_works&sortby=pubdate) profile
